; ESP32-C3 Super Mini + Ai-Thinker Ra-01SH-P (SX1262 + internal +29dBm FEM)
[env:esp32c3_super_mini_ra01sh_p]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags =
  ${esp32c3_base.build_flags}
  -D PRIVATE_HW
  -D AI_THINKER_RA01SH_P
  -D MESHTASTIC_EXCLUDE_XEDDSA=1 ; unsigned broadcasts: signed ones are not relayed by meshes on stable firmware
  -I variants/esp32c3/diy/esp32c3_super_mini_ra01sh_p
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
board_level = extra
